# Generated by Django 4.2.7 on 2025-05-29 16:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import resumes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=resumes.models.get_resume_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), resumes.models.validate_file_size, resumes.models.validate_file_content])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=resumes.models.get_jd_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), resumes.models.validate_file_size, resumes.models.validate_file_content])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('job_type', models.CharField(blank=True, choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract'), ('INTERNSHIP', 'Internship'), ('REMOTE', 'Remote')], max_length=50, null=True)),
                ('experience_level', models.CharField(blank=True, choices=[('ENTRY', 'Entry Level'), ('MID', 'Mid Level'), ('SENIOR', 'Senior Level'), ('LEAD', 'Lead Level'), ('MANAGER', 'Manager Level')], max_length=50, null=True)),
                ('required_skills', models.TextField(blank=True, help_text='Comma-separated list of required skills', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
