# Generated by Django 5.2 on 2025-05-27 11:25

import django.core.validators
import resumes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobdescription',
            old_name='company',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='file',
            field=models.FileField(upload_to='jds/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx']), resumes.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(upload_to='resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx']), resumes.models.validate_file_size]),
        ),
    ]
