# Generated by Django 5.2 on 2025-05-07 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobdescription',
            old_name='company',
            new_name='user',
        ),
    ]
