# Generated by Django 4.2.7 on 2025-05-28 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_rename_company_jobdescription_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('ENTRY', 'Entry Level'), ('MID', 'Mid Level'), ('SENIOR', 'Senior Level'), ('LEAD', 'Lead Level'), ('MANAGER', 'Manager Level')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='job_type',
            field=models.CharField(blank=True, choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('CONTRACT', 'Contract'), ('INTERNSHIP', 'Internship'), ('REMOTE', 'Remote')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='required_skills',
            field=models.TextField(blank=True, help_text='Comma-separated list of required skills', null=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SimilarityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_scores', to='resumes.jobdescription')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_scores', to='resumes.resume')),
            ],
            options={
                'ordering': ['-score'],
                'unique_together': {('resume', 'job_description')},
            },
        ),
    ]
