# Generated by Django 4.2.7 on 2025-05-29 04:34

import django.core.validators
from django.db import migrations, models
import resumes.models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_jobdescription_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='resume',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='file',
            field=models.FileField(upload_to=resumes.models.get_jd_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx']), resumes.models.validate_file_size, resumes.models.validate_file_content]),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(upload_to=resumes.models.get_resume_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx']), resumes.models.validate_file_size, resumes.models.validate_file_content]),
        ),
    ]
