# Generated by Django 4.2.7 on 2025-05-29 04:38

import django.core.validators
from django.db import migrations, models
import resumes.models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_jobdescription_original_filename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdescription',
            name='file',
            field=models.FileField(upload_to=resumes.models.get_jd_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), resumes.models.validate_file_size, resumes.models.validate_file_content]),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(upload_to=resumes.models.get_resume_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), resumes.models.validate_file_size, resumes.models.validate_file_content]),
        ),
    ]
