# Generated by Django 4.2.7 on 2025-05-29 04:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0005_alter_jobdescription_file_alter_resume_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='similarityscore',
            name='score',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0, message='Score cannot be less than 0'), django.core.validators.MaxValueValidator(1.0, message='Score cannot be greater than 1')]),
        ),
        migrations.AddIndex(
            model_name='similarityscore',
            index=models.Index(fields=['resume', 'job_description'], name='resumes_sim_resume__0ee865_idx'),
        ),
        migrations.AddIndex(
            model_name='similarityscore',
            index=models.Index(fields=['score'], name='resumes_sim_score_fa4130_idx'),
        ),
    ]
