# Generated by Django 4.2.7 on 2025-05-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='education',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='preferred_job_types',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='preferred_locations',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='company_description',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='company_location',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='company_size',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='company_website',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='industry',
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('candidate', 'Candidate'), ('company', 'Company')], default='candidate', max_length=10),
        ),
    ]
