# Generated by Django 4.2.7 on 2025-06-07 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserHistory',
        ),
    ]
