# Generated by Django 4.2.7 on 2025-05-29 16:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0, message='Score must be >= 0.0'), django.core.validators.MaxValueValidator(1.0, message='Score must be <= 1.0')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_scores', to='resumes.jobdescription')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_scores', to='resumes.resume')),
            ],
            options={
                'ordering': ['-score'],
                'indexes': [models.Index(fields=['resume', 'job_description'], name='matcher_sim_resume__8dbce3_idx'), models.Index(fields=['score'], name='matcher_sim_score_954967_idx')],
                'unique_together': {('resume', 'job_description')},
            },
        ),
    ]
